apiVersion: v1
kind: Namespace
metadata:
  name: ai
---
apiVersion: v1
kind: Secret
metadata:
  name: ai-secrets
  namespace: ai
type: Opaque
stringData:
  postgres-db: "ai_db"
  postgres-user: "database_user"
  postgres-password: "secure_password"
